import { t } from "../lib/i18n"

export function getSettingsUi(lang: string) {
  if (lang === "de") {
    return {
      subtitle: "Einstellungen, Verhalten und Projektinfos an einem Ort.",
      general: "Allgemein",
      generalDesc: "Sprache, Theme und grundlegende App Optionen.",
      securityTitle: "Security",
      securityDesc: "Optionaler Passwortschutz für gespeicherte Secrets im lokalen Vault.",
      securityStatusLabel: "Vault Status",
      securityStatusOff: "Passwortschutz aus",
      securityStatusOn: "Passwortschutz an",
      securityStatusLocked: "Gesperrt",
      securityStatusUnlocked: "Entsperrt",
      securityProtectedDesc: "Passwörter und Passphrases werden über den Vault geschützt.",
      securityNotProtectedDesc: "Der Vault läuft normal ohne Passwortschutz.",
      securityLegacyTitle: "Legacy Hinweis",
      securityLegacyDesc: "Ein alter lokaler Secret Rest wurde gefunden. Er ist nicht mehr der aktive Live Speicher.",
      securitySetupTitle: "Vault aktivieren",
      securitySetupDesc: "Aktiviere den Schutz nur einmal. Danach kannst du den Vault bei Bedarf entsperren oder sperren.",
      securityModeLabel: "Unlock Mode",
      securityCurrentModeDesc: "Aktueller Modus des lokalen Vault.",
      securityModeDemand: "On demand",
      securityModeStartup: "On startup",
      securityModeDemandDesc: "Der Vault wird nur entsperrt, wenn du ihn wirklich brauchst.",
      securityModeStartupDesc: "Der Vault wird direkt nach dem Entsperren am App Start genutzt.",
      securityEnableTitle: "Passwortschutz einschalten",
      securityEnableDesc: "Lege ein Master Passwort für deinen Vault fest.",
      securityEnableAction: "Einschalten",
      securityUnlockTitle: "Vault entsperren",
      securityUnlockDesc: "Gib dein Master Passwort ein.",
      securityUnlockAction: "Entsperren",
      securityLockAction: "Sperren",
      securityActionsTitle: "Aktionen",
      securityActionsLockedDesc: "Der Vault ist aktiv, aber aktuell gesperrt.",
      securityActionsUnlockedDesc: "Der Vault ist aktiv und aktuell entsperrt.",
      securityMasterPasswordPlaceholder: "Master Passwort",
      securityMasterPasswordConfirmPlaceholder: "Master Passwort bestätigen",
      securityMasterPasswordEmpty: "Bitte ein Master Passwort eingeben.",
      securityMasterPasswordTooShort: "Bitte mindestens 6 Zeichen verwenden.",
      securityMasterPasswordMismatch: "Die Passwörter stimmen nicht überein.",
      securityRecoveryHint: "Zusätzlich wird ein Recovery Key für Backup und Notfälle erzeugt. Bewahre ihn sicher auf.",
      securityRecoveryTitle: "Recovery Key",
      securityRecoveryDesc: "Speichere diesen Recovery Key als Backup an einem sicheren Ort.",
      securityRecoveryCopied: "Recovery Key kopiert!",
      securityMigratedPrefix: "Migrierte Secret Einträge",
      securityEnabledToast: "Passwortschutz eingeschaltet",
      securityUnlockedToast: "Vault entsperrt",
      securityLockedToast: "Vault gesperrt",
      refreshLabel: "Aktualisieren",
      closeLabel: "Schließen",
      copyLabel: "Kopieren",
      interface: "Oberfläche",
      interfaceDesc: "Steuere die aktuell verfügbaren Werkzeuge in der Terminal Leiste.",
      dashboardTitle: "Dashboard",
      dashboardDesc: "Lege fest, welche Bereiche auf der Startseite sichtbar sind.",
      showDashboardQuickConnectLabel: "Quick Connect anzeigen",
      showDashboardQuickConnectDesc: "Blendet die Quick Connect Box auf der Startseite ein oder aus.",
      showDashboardWorkflowLabel: "Workflow Übersicht anzeigen",
      showDashboardWorkflowDesc: "Zeigt die große Workflow Box mit Local Terminal und den Kennzahlen.",
      showDashboardActiveSessionsLabel: "Active Sessions anzeigen",
      showDashboardActiveSessionsDesc: "Blendet die Box mit den aktuell offenen Sessions ein oder aus.",
      showDashboardRecentConnectionsLabel: "Recent Connections anzeigen",
      showDashboardRecentConnectionsDesc: "Blendet die Box mit den zuletzt verwendeten Verbindungen ein oder aus.",
      statusBar: "Status Bar",
      statusBarDesc: "Lege fest, welche Infos unten im Terminal sichtbar sind.",
      terminalDesc: "Darstellung und Verhalten des Terminals.",
      showStatusBarLabel: "Status Bar anzeigen",
      showStatusBarLabelDesc: "Blendet die Leiste am unteren Rand des Terminals ein oder aus.",
      showStatusBarSessionLabel: "Session Zeit anzeigen",
      showStatusBarSessionLabelDesc: "Zeigt links die Laufzeit der aktuellen Session.",
      showStatusBarTunnelLabel: "Tunnel Status anzeigen",
      showStatusBarTunnelLabelDesc: "Zeigt mittig aktive Tunnel nur dann, wenn wirklich einer läuft.",
      showStatusBarLoadLabel: "Load anzeigen",
      showStatusBarLoadLabelDesc: "Zeigt rechts die Systemlast, sobald diese Info verfügbar ist.",
      showStatusBarRamLabel: "RAM anzeigen",
      showStatusBarRamLabelDesc: "Zeigt rechts die RAM Nutzung, sobald diese Info verfügbar ist.",
      sftpDesc: "Standardverhalten für den SFTP Browser.",
      keysDesc: "Verwalte deine gespeicherten SSH Schlüssel.",
      backupDescTitle: "Sichert Einstellungen, Verbindungen, Snippets und SSH Schlüssel.",
      about: "About",
      aboutDesc: "Projektinfo, kurzer Überblick und Support Link.",
      appLanguageDesc: "Sprache der Oberfläche.",
      themeDesc: "Aktuelles Farbschema der App.",
      closeToTrayLabel: "In Tray schließen",
      closeToTrayDesc: "Fenster beim Schließen ausblenden. Beenden über den Tray.",
      terminalToolsDesc: "Aktuell werden nur wirklich funktionierende Werkzeuge angezeigt.",
      fontSizeDesc: "Schriftgröße im Terminal.",
      scrollbackDesc: "Wie viele Zeilen im Verlauf gehalten werden.",
      cursorStyleDesc: "Form des Terminal Cursors.",
      cursorBlinkDesc: "Cursor blinkt im Terminal.",
      showHiddenDesc: "Versteckte Dateien standardmäßig anzeigen.",
      sortOrderDesc: "Standard Sortierung im SFTP Browser.",
      noKeys: "Keine Schlüssel vorhanden.",
      noKeysHint: "Erzeuge einen neuen Schlüssel oder importiere einen vorhandenen.",
      generated: "Schlüssel generiert!",
      imported: "Schlüssel importiert!",
      exported: "Backup exportiert!",
      importedBackup: "Backup importiert!",
      wrongPassword: "Falsches Passwort!",
      importedLabel: "Importiert",
      toolsSection: "Werkzeuge",
      projectTitle: "Termina SSH",
      projectText:
        "Termina SSH ist ein moderner Desktop SSH Client mit Fokus auf einen ruhigen Workflow, schnelle Sessions, integrierten SFTP Zugriff und einen eingebauten Editor. Das Ziel ist ein Daily Driver, der sich stabil, schnell und angenehm anfühlt.",
      supportTitle: "Support",
      supportText: "Wenn dir das Projekt gefällt und du die Weiterentwicklung unterstützen willst, kannst du mir auf Ko fi einen Kaffee spendieren.",
      openKofi: "Ko fi öffnen",
      copyLink: "Link kopieren",
      copiedLink: "Link kopiert!",
      versionLabel: "Projektstatus",
      versionValue: "Kern Workflow ist stabil und wird aktiv erweitert.",
      settingsTitle: t("settings", lang)
    }
  }

  return {
    subtitle: "Settings, behavior and project info in one place.",
    general: "General",
    generalDesc: "Language, theme and core app options.",
    securityTitle: "Security",
    securityDesc: "Optional password protection for stored secrets in the local vault.",
    securityStatusLabel: "Vault status",
    securityStatusOff: "Password protection off",
    securityStatusOn: "Password protection on",
    securityStatusLocked: "Locked",
    securityStatusUnlocked: "Unlocked",
    securityProtectedDesc: "Passwords and passphrases are protected through the vault.",
    securityNotProtectedDesc: "The vault is working normally without password protection.",
    securityLegacyTitle: "Legacy note",
    securityLegacyDesc: "An old local secret remnant was found. It is no longer used as the live secret store.",
    securitySetupTitle: "Enable vault",
    securitySetupDesc: "Enable protection once. After that, you can unlock or lock the vault when needed.",
    securityModeLabel: "Unlock mode",
    securityCurrentModeDesc: "Current mode of the local vault.",
    securityModeDemand: "On demand",
    securityModeStartup: "On startup",
    securityModeDemandDesc: "The vault is only unlocked when you really need it.",
    securityModeStartupDesc: "The vault is intended to be used right after unlock during app startup.",
    securityEnableTitle: "Turn on password protection",
    securityEnableDesc: "Add a master password to your vault.",
    securityEnableAction: "Turn on",
    securityUnlockTitle: "Unlock vault",
    securityUnlockDesc: "Enter your master password.",
    securityUnlockAction: "Unlock",
    securityLockAction: "Lock",
    securityActionsTitle: "Actions",
    securityActionsLockedDesc: "The vault is enabled, but currently locked.",
    securityActionsUnlockedDesc: "The vault is enabled and currently unlocked.",
    securityMasterPasswordPlaceholder: "Master password",
    securityMasterPasswordConfirmPlaceholder: "Confirm master password",
    securityMasterPasswordEmpty: "Please enter a master password.",
    securityMasterPasswordTooShort: "Please use at least 6 characters.",
    securityMasterPasswordMismatch: "The passwords do not match.",
    securityRecoveryHint: "A recovery key will also be created for backup and emergencies. Store it safely.",
    securityRecoveryTitle: "Recovery key",
    securityRecoveryDesc: "Save this recovery key somewhere safe as a backup.",
    securityRecoveryCopied: "Recovery key copied!",
    securityMigratedPrefix: "Migrated secret entries",
    securityEnabledToast: "Password protection turned on",
    securityUnlockedToast: "Vault unlocked",
    securityLockedToast: "Vault locked",
    refreshLabel: "Refresh",
    closeLabel: "Close",
    copyLabel: "Copy",
    interface: "Interface",
    interfaceDesc: "Control the tools that are currently available in the terminal header.",
    dashboardTitle: "Dashboard",
    dashboardDesc: "Choose which sections are visible on the start page.",
    showDashboardQuickConnectLabel: "Show Quick Connect",
    showDashboardQuickConnectDesc: "Shows or hides the Quick Connect box on the start page.",
    showDashboardWorkflowLabel: "Show workflow overview",
    showDashboardWorkflowDesc: "Shows the large workflow box with Local Terminal and the quick counters.",
    showDashboardActiveSessionsLabel: "Show Active Sessions",
    showDashboardActiveSessionsDesc: "Shows or hides the card with the currently open sessions.",
    showDashboardRecentConnectionsLabel: "Show Recent Connections",
    showDashboardRecentConnectionsDesc: "Shows or hides the card with the recently used connections.",
    statusBar: "Status Bar",
    statusBarDesc: "Choose which details are visible at the bottom of the terminal.",
    terminalDesc: "Appearance and behavior of the terminal.",
    showStatusBarLabel: "Show status bar",
    showStatusBarLabelDesc: "Shows or hides the bar at the bottom of the terminal.",
    showStatusBarSessionLabel: "Show session timer",
    showStatusBarSessionLabelDesc: "Shows the current session duration on the left.",
    showStatusBarTunnelLabel: "Show tunnel status",
    showStatusBarTunnelLabelDesc: "Shows active tunnel info in the center only when a tunnel is really active.",
    showStatusBarLoadLabel: "Show load",
    showStatusBarLoadLabelDesc: "Shows system load on the right as soon as that info is available.",
    showStatusBarRamLabel: "Show RAM",
    showStatusBarRamLabelDesc: "Shows RAM usage on the right as soon as that info is available.",
    sftpDesc: "Default behavior for the SFTP browser.",
    keysDesc: "Manage your stored SSH keys.",
    backupDescTitle: "Backs up settings, connections, snippets and SSH keys.",
    about: "About",
    aboutDesc: "Project info, short overview and support link.",
    appLanguageDesc: "Language of the interface.",
    themeDesc: "Current color theme of the app.",
    closeToTrayLabel: "Close to tray",
    closeToTrayDesc: "Hide window on close. Quit from tray.",
    terminalToolsDesc: "Only tools that are already fully working are shown here right now.",
    fontSizeDesc: "Terminal font size.",
    scrollbackDesc: "How many lines are kept in history.",
    cursorStyleDesc: "Shape of the terminal cursor.",
    cursorBlinkDesc: "Blinking terminal cursor.",
    showHiddenDesc: "Show hidden files by default.",
    sortOrderDesc: "Default sorting in the SFTP browser.",
    noKeys: "No keys available.",
    noKeysHint: "Generate a new key or import an existing one.",
    generated: "Key generated!",
    imported: "Key imported!",
    exported: "Backup exported!",
    importedBackup: "Backup imported!",
    wrongPassword: "Wrong password!",
    importedLabel: "Imported",
    toolsSection: "Tools",
    projectTitle: "Termina SSH",
    projectText:
      "Termina SSH is a modern desktop SSH client focused on a calm workflow, fast sessions, integrated SFTP access and a built in editor. The goal is a daily driver that feels stable, fast and pleasant to use.",
    supportTitle: "Support",
    supportText: "If you enjoy the project and want to support further development, you can buy me a coffee on Ko fi.",
    openKofi: "Open Ko fi",
    copyLink: "Copy link",
    copiedLink: "Link copied!",
    versionLabel: "Project status",
    versionValue: "Core workflow is stable and actively expanding.",
    settingsTitle: t("settings", lang)
  }
}
