import { t } from "../lib/i18n"

export function getSettingsUi(lang: string) {
  if (lang === "de") {
    return {
      subtitle: "App Optionen und Verhalten.",
      general: "Allgemein",
      generalDesc: "Sprache, Theme und App Optionen.",
      securityTitle: "Security",
      securityDesc: "Schützt gespeicherte Secrets im Vault.",
      securityStatusLabel: "Vault Status",
      securityStatusOff: "Passwortschutz aus",
      securityStatusOn: "Passwortschutz an",
      securityStatusLocked: "Gesperrt",
      securityStatusUnlocked: "Entsperrt",
      securityProtectedDesc: "Vault mit Passwortschutz.",
      securityNotProtectedDesc: "Vault ohne Passwortschutz.",
      securityLegacyTitle: "Legacy Hinweis",
      securityLegacyDesc: "Alte lokale Secrets gefunden. Nicht mehr aktiv.",
      securitySetupTitle: "Vault aktivieren",
      securitySetupDesc: "Schutz aktivieren und bei Bedarf entsperren.",
      securityModeLabel: "Unlock Mode",
      securityCurrentModeDesc: "Aktueller Vault Modus.",
      securityModeDemand: "On demand",
      securityModeStartup: "On startup",
      securityModeDemandDesc: "Nur bei Bedarf entsperren.",
      securityModeStartupDesc: "Beim Start nach Entsperren nutzen.",
      securityEnableTitle: "Passwortschutz einschalten",
      securityEnableDesc: "Lege ein Master Passwort für deinen Vault fest.",
      securityEnableAction: "Einschalten",
      securityUnlockTitle: "Vault entsperren",
      securityUnlockDesc: "Gib dein Master Passwort ein.",
      securityUnlockAction: "Entsperren",
      securityLockAction: "Sperren",
      securityActionsTitle: "Aktionen",
      securityActionsLockedDesc: "Der Vault ist aktiv, aber aktuell gesperrt.",
      securityActionsUnlockedDesc: "Der Vault ist aktiv und aktuell entsperrt.",
      securityMasterPasswordPlaceholder: "Master Passwort",
      securityMasterPasswordConfirmPlaceholder: "Master Passwort bestätigen",
      securityMasterPasswordEmpty: "Bitte ein Master Passwort eingeben.",
      securityMasterPasswordTooShort: "Bitte mindestens 6 Zeichen verwenden.",
      securityMasterPasswordMismatch: "Die Passwörter stimmen nicht überein.",
      securityRecoveryHint: "Es wird auch ein Recovery Key erzeugt. Sicher aufbewahren.",
      securityRecoveryTitle: "Recovery Key",
      securityRecoveryDesc: "Speichere diesen Recovery Key als Backup an einem sicheren Ort.",
      securityRecoveryCopied: "Recovery Key kopiert!",
      securityMigratedPrefix: "Migrierte Secret Einträge",
      securityEnabledToast: "Passwortschutz eingeschaltet",
      securityUnlockedToast: "Vault entsperrt",
      securityLockedToast: "Vault gesperrt",
      refreshLabel: "Aktualisieren",
      closeLabel: "Schließen",
      copyLabel: "Kopieren",
      interface: "Oberfläche",
      interfaceDesc: "Werkzeuge in der Leiste.",
      dashboardTitle: "Dashboard",
      dashboardDesc: "Sichtbare Bereiche auf der Startseite.",
      showDashboardQuickConnectLabel: "Quick Connect anzeigen",
      showDashboardQuickConnectDesc: "Quick Connect auf der Startseite.",
      showDashboardWorkflowLabel: "Workflow Übersicht anzeigen",
      showDashboardWorkflowDesc: "Workflow Box auf der Startseite.",
      showDashboardActiveSessionsLabel: "Active Sessions anzeigen",
      showDashboardActiveSessionsDesc: "Offene Sessions auf der Startseite.",
      showDashboardRecentConnectionsLabel: "Recent Connections anzeigen",
      showDashboardRecentConnectionsDesc: "Letzte Verbindungen auf der Startseite.",
      statusBar: "Status Bar",
      statusBarDesc: "Infos am unteren Rand des Terminals.",
      terminalDesc: "Terminal Darstellung und Verhalten.",
      showStatusBarLabel: "Status Bar anzeigen",
      showStatusBarLabelDesc: "Leiste unten im Terminal.",
      showFileBrowserStatusBarLabel: "File Browser Status Bar anzeigen",
      showFileBrowserStatusBarLabelDesc: "Leiste unten im Datei Browser.",
      showStatusBarSessionLabel: "Session Zeit anzeigen",
      showStatusBarSessionLabelDesc: "Session Zeit links.",
      showStatusBarTunnelLabel: "Tunnel Status anzeigen",
      showStatusBarTunnelLabelDesc: "Aktive Tunnel in der Mitte.",
      showStatusBarLoadLabel: "Load anzeigen",
      showStatusBarLoadLabelDesc: "Systemlast rechts.",
      showStatusBarRamLabel: "RAM anzeigen",
      showStatusBarRamLabelDesc: "RAM Nutzung rechts.",
      sftpDesc: "Standardverhalten im Datei Browser.",
      keysDesc: "Gespeicherte SSH Schlüssel.",
      backupDescTitle: "Export und Import für App Daten.",
      about: "About",
      aboutDesc: "Projektinfo und Links.",
      appLanguageDesc: "Sprache der App.",
      themeDesc: "Farbschema der App.",
      closeToTrayLabel: "In Tray schließen",
      closeToTrayDesc: "Fenster nur ausblenden.",
      terminalToolsDesc: "Nur verfügbare Werkzeuge.",
      fontSizeDesc: "Schriftgröße.",
      scrollbackDesc: "Zeilen im Verlauf.",
      cursorStyleDesc: "Cursor Form.",
      cursorBlinkDesc: "Cursor blinkt.",
      showHiddenDesc: "Versteckte Dateien anzeigen.",
      sortOrderDesc: "Standard Sortierung.",
      noKeys: "Keine Schlüssel vorhanden.",
      noKeysHint: "Erzeuge einen neuen Schlüssel oder importiere einen vorhandenen.",
      generated: "Schlüssel generiert!",
      imported: "Schlüssel importiert!",
      exported: "Backup exportiert!",
      importedBackup: "Backup importiert!",
      wrongPassword: "Falsches Passwort!",
      importedLabel: "Importiert",
      toolsSection: "Werkzeuge",
      projectTitle: "Termina SSH",
      projectText:
        "Moderner Desktop SSH Client mit schnellem Workflow, SFTP und Editor.",
      supportTitle: "Support",
      supportText: "Unterstütze die Weiterentwicklung auf Ko fi.",
      openKofi: "Ko fi öffnen",
      copyLink: "Link kopieren",
      copiedLink: "Link kopiert!",
      versionLabel: "Projektstatus",
      versionValue: "Kern Workflow stabil.",
      settingsTitle: t("settings", lang)
    }
  }

  return {
    subtitle: "App options and behavior.",
    general: "General",
    generalDesc: "Language, theme, and app options.",
    securityTitle: "Security",
    securityDesc: "Protects stored secrets in the vault.",
    securityStatusLabel: "Vault status",
    securityStatusOff: "Password protection off",
    securityStatusOn: "Password protection on",
    securityStatusLocked: "Locked",
    securityStatusUnlocked: "Unlocked",
    securityProtectedDesc: "Vault with password protection.",
    securityNotProtectedDesc: "Vault without password protection.",
    securityLegacyTitle: "Legacy note",
    securityLegacyDesc: "Old local secrets found. No longer active.",
    securitySetupTitle: "Enable vault",
    securitySetupDesc: "Enable protection and unlock it when needed.",
    securityModeLabel: "Unlock mode",
    securityCurrentModeDesc: "Current vault mode.",
    securityModeDemand: "On demand",
    securityModeStartup: "On startup",
    securityModeDemandDesc: "Unlock only when needed.",
    securityModeStartupDesc: "Use on startup after unlock.",
    securityEnableTitle: "Turn on password protection",
    securityEnableDesc: "Add a master password to your vault.",
    securityEnableAction: "Turn on",
    securityUnlockTitle: "Unlock vault",
    securityUnlockDesc: "Enter your master password.",
    securityUnlockAction: "Unlock",
    securityLockAction: "Lock",
    securityActionsTitle: "Actions",
    securityActionsLockedDesc: "The vault is enabled, but currently locked.",
    securityActionsUnlockedDesc: "The vault is enabled and currently unlocked.",
    securityMasterPasswordPlaceholder: "Master password",
    securityMasterPasswordConfirmPlaceholder: "Confirm master password",
    securityMasterPasswordEmpty: "Please enter a master password.",
    securityMasterPasswordTooShort: "Please use at least 6 characters.",
    securityMasterPasswordMismatch: "The passwords do not match.",
    securityRecoveryHint: "A recovery key is also created. Store it safely.",
    securityRecoveryTitle: "Recovery key",
    securityRecoveryDesc: "Save this recovery key somewhere safe as a backup.",
    securityRecoveryCopied: "Recovery key copied!",
    securityMigratedPrefix: "Migrated secret entries",
    securityEnabledToast: "Password protection turned on",
    securityUnlockedToast: "Vault unlocked",
    securityLockedToast: "Vault locked",
    refreshLabel: "Refresh",
    closeLabel: "Close",
    copyLabel: "Copy",
    interface: "Interface",
    interfaceDesc: "Tools in the header.",
    dashboardTitle: "Dashboard",
    dashboardDesc: "Visible sections on the home screen.",
    showDashboardQuickConnectLabel: "Show Quick Connect",
    showDashboardQuickConnectDesc: "Quick Connect on the home screen.",
    showDashboardWorkflowLabel: "Show workflow overview",
    showDashboardWorkflowDesc: "Workflow card on the home screen.",
    showDashboardActiveSessionsLabel: "Show Active Sessions",
    showDashboardActiveSessionsDesc: "Open sessions on the home screen.",
    showDashboardRecentConnectionsLabel: "Show Recent Connections",
    showDashboardRecentConnectionsDesc: "Recent connections on the home screen.",
    statusBar: "Status Bar",
    statusBarDesc: "Info shown at the bottom of the terminal.",
    terminalDesc: "Terminal appearance and behavior.",
    showStatusBarLabel: "Show status bar",
    showStatusBarLabelDesc: "Bar at the bottom of the terminal.",
    showFileBrowserStatusBarLabel: "Show file browser status bar",
    showFileBrowserStatusBarLabelDesc: "Bar at the bottom of the file browser.",
    showStatusBarSessionLabel: "Show session timer",
    showStatusBarSessionLabelDesc: "Session timer on the left.",
    showStatusBarTunnelLabel: "Show tunnel status",
    showStatusBarTunnelLabelDesc: "Active tunnels in the center.",
    showStatusBarLoadLabel: "Show load",
    showStatusBarLoadLabelDesc: "System load on the right.",
    showStatusBarRamLabel: "Show RAM",
    showStatusBarRamLabelDesc: "RAM usage on the right.",
    sftpDesc: "Default behavior in the file browser.",
    keysDesc: "Stored SSH keys.",
    backupDescTitle: "Export and import for app data.",
    about: "About",
    aboutDesc: "Project info and links.",
    appLanguageDesc: "App language.",
    themeDesc: "App color theme.",
    closeToTrayLabel: "Close to tray",
    closeToTrayDesc: "Hide the window on close.",
    terminalToolsDesc: "Only available tools.",
    fontSizeDesc: "Font size.",
    scrollbackDesc: "Lines kept in history.",
    cursorStyleDesc: "Cursor shape.",
    cursorBlinkDesc: "Blinking cursor.",
    showHiddenDesc: "Show hidden files.",
    sortOrderDesc: "Default sorting.",
    noKeys: "No keys available.",
    noKeysHint: "Generate a new key or import an existing one.",
    generated: "Key generated!",
    imported: "Key imported!",
    exported: "Backup exported!",
    importedBackup: "Backup imported!",
    wrongPassword: "Wrong password!",
    importedLabel: "Imported",
    toolsSection: "Tools",
    projectTitle: "Termina SSH",
    projectText:
      "Modern desktop SSH client with fast workflow, SFTP, and editor.",
    supportTitle: "Support",
    supportText: "Support development on Ko fi.",
    openKofi: "Open Ko fi",
    copyLink: "Copy link",
    copiedLink: "Link copied!",
    versionLabel: "Project status",
    versionValue: "Core workflow is stable.",
    settingsTitle: t("settings", lang)
  }
}
